// src/components/CardChat.vue
<script setup>

</script>

<template>
  <div class="chat chat-start">
    <div class="chat-bubble">It's over Anakin.</div>
  </div>
  <div class="chat chat-end">
    <div class="chat-bubble">You underestimate my power!</div>
  </div>
  <br>
  <input type="text" placeholder="Enviar mensagem" class="input input-bordered w-full max-w-xs mr-3" />
  <button class="btn">Enviar</button>
</template>

<style scoped></style>

// src/app/components/card-chat/card-chat.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-card-chat',
  templateUrl: './card-chat.component.html',
  styleUrls: ['./card-chat.component.css']
})
export class CardChatComponent {

}

<div class="chat chat-start">
  <div class="chat-bubble">It's over Anakin.</div>
</div>
<div class="chat chat-end">
  <div class="chat-bubble">You underestimate my power!</div>
</div>
<br />
<input
  type="text"
  placeholder="Enviar mensagem"
  class="input input-bordered w-full max-w-xs mr-3"
/>
<button class="btn">Enviar</button>
